### ISSUE TITLE
Bitmap Generation is Incorrect due to DIB Header Size

### ISSUE THREAD

**Issue by EBrown8534** [ChrisPritchard/Heightmaps#1]
https://github.com/ChrisPritchard/Heightmaps/blob/12a7853dbc413f79b0eaa94bc29bbbcebe4ea202/BMP.fs#L44

You need `dib.Length + 4`, because you don't have the size of the DIB header in it, so you have to account for it extraneously.

**Comment by ChrisPritchard** [comment]
Cheers, implemented. Padding also had (several) faults, which caused some funny artefacts.
